"""
lang.py —  kullanıcı arayüzü dil paketleri.
"""

LANG = {
    "TR": {
        "app_title":        "✉  Haber Bülteni Editörü",
        "editor_title":     "✉  BÜLTEN EDİTÖRÜ",
        "preview_lbl":      "ÖNİZLEME",
        "newsletter_info":  "BÜLTEN BİLGİLERİ",
        "subject_ph":       "Konu satırı / Bülten başlığı",
        "header_grp":       "HEADER",
        "footer_grp":       "FOOTER",
        "colors_grp":       "GENEL RENKLER",
        "add_block_grp":    "BLOK EKLE",
        "content_lbl":      "İÇERİK BLOKLARI",
        "no_img":           "Görsel seçilmedi",
        "img_sel":          "📎 PNG Seç",
        "img_clr":          "✕ Temizle",
        "bg_color_lbl":     "İçerik Kutusu Arka Planı — Kurumsal Öneriler:",
        "accent_lbl":       "Vurgu / Başlık Rengi:",
        "custom_color":     "Özel →",
        "header_bg_lbl":    "Arka Plan:",
        "header_txt_lbl":   "Yazı Rengi:",
        "footer_text_ph":   "Footer metni...",
        "footer_bg_lbl":    "Arka Plan:",
        "footer_txt_lbl":   "Yazı Rengi:",
        "btn_clear":        "🗑  Temizle",
        "btn_load":         "📂  Yükle",
        "btn_save_proj":    "💾  Proje Kaydet",
        "btn_export":       "⬇  HTML İndir",
        "btn_copy":         "📋  HTML Kopyala",
        "btn_refresh":      "🔄",
        "clear_confirm":    "Tüm bloklar silinsin mi?",
        "clear_title":      "Temizle",
        "saved_title":      "Kaydedildi",
        "saved_msg":        "Dosya kaydedildi:\n{}",
        "proj_saved":       "Proje kaydedildi.",
        "copied_title":     "Kopyalandı",
        "copied_msg":       "HTML panoya kopyalandı.",
        "error_title":      "Hata",
        "block_add_err":    "Blok eklenemedi:\n{}",
        "export_err":       "Dışa aktarma hatası:\n{}",
        "html_err":         "HTML üretim hatası:<br>{}",
        "no_block_lbl":     "Henüz blok yok.\nYukarıdan ekleyin ↑",
        "footer_default":   "Bu e-posta otomatik olarak gönderilmiştir. | © 2025 Şirketiniz",
        "block_heading":    "📌 Başlık",
        "block_paragraph":  "📝 Paragraf",
        "block_quote":      "❝ Alıntı",
        "block_bullet":     "• Madde",
        "block_numbered":   "1. Numaralı",
        "block_divider":    "─ Ayraç",
        "block_button":     "🔗 Buton",
        "block_image_url":  "🖼 Görsel URL",
        "block_image_file": "🖼 Görsel Dosya",
        "block_spacer":     "↕ Boşluk",
        "ph_heading":       "Başlık metni...",
        "ph_paragraph":     "Metin...",
        "ph_quote":         "Alıntı...",
        "ph_list":          "Her satır bir madde",
        "ph_btn_text":      "Buton metni",
        "ph_btn_url":       "https://ornek.com",
        "ph_img_url":       "https://domain.com/resim.jpg",
        "ph_img_alt":       "Açıklama (opsiyonel)",
        "img_select_btn":   "📁 Dosya Seç",
        "img_file_lbl":     "Dosya seçilmedi",
        "height_lbl":       "Yükseklik (px):",
        "btn_text_lbl":     "Metin:",
        "btn_url_lbl":      "URL:",
        "lang_btn":         "🌐 English",
        "email_footer":     "Bu e-posta otomatik olarak gönderilmiştir.",
        "two_col":          "2 Sütun",
        "one_col":          "1 Sütun",
        "col_lbl":          "Sütun:",
        "hide_subject":     "Başlığı Gizle",
        "hide_footer_txt":  "Alt Yazıyı Gizle",
        "btn_apply":        "✔ Uygula",
        "font_size_lbl":    "Punto:",
        "font_family_lbl":  "Font:",
        "btn_clear_content":"🧹 İçeriği Temizle",
        "fonts_grp":        "YAZI TİPİ & PUNTO",
        "block_url_ph":     "https:// (opsiyonel bağlantı)",
        "block_url_lbl":    "🔗 URL:",

        "block_section":    "🎨 Bölüm (Koyu Alan)",
        "block_toc":        "📋 İçindekiler",
        "block_highlight":  "💡 Highlight Kutu",
        "block_table":      "📊 Tablo",
        "block_cards":      "👤 Kişi Kartları",
        "block_emoji_row":  "😊 Emoji Satırı",
        "hl_success":       "✅ Başarı (Yeşil)",
        "hl_warning":       "⚠️ Uyarı (Kırmızı)",
        "hl_info":          "ℹ️ Bilgi (Mavi)",
        "hl_neutral":       "◻️ Nötr (Gri)",
        "hl_type_lbl":      "Tür:",
        "hl_title_ph":      "Başlık...",
        "hl_body_ph":       "Açıklama...",
        "toc_items_ph":     "Başlık 1\nBaşlık 2\nBaşlık 3",
        "toc_cols_lbl":     "Sütun sayısı:",
        "toc_txt_lbl":      "Yazı Rengi:",
        "toc_bg_lbl":       "Kutu Arkaplanı:",
        "toc_border_lbl":   "Kenarlık Rengi:",
        "tbl_cols_ph":      "Kategori,Program,Durum,Kaynak",
        "tbl_rows_ph":      "Satır1Col1,Satır1Col2,Satır1Col3,Satır1Col4\nSatır2Col1,...",
        "card_items_ph":    "Ad Soyad|Unvan|email@ornek.com\nAd Soyad|Unvan|email@ornek.com",
        "card_cols_lbl":    "Sütun:",
        "card_bg_lbl":      "Kart Arkaplanı:",
        "card_border_lbl":  "Kenarlık:",
        "card_avatar_lbl":  "Avatar:",
        "card_name_lbl":    "İsim Rengi:",
        "card_role_lbl":    "Unvan Rengi:",
        "card_email_lbl":   "E-posta Rengi:",
        "emoji_ph":         "😊 👍 🎉 💡",
        "section_bg_lbl":   "Bölüm Rengi:",
        "section_txt_lbl":  "Yazı Rengi:",
        "section_label_ph": "Küçük etiket (ör. QUICK BRIEFING)",
        "section_title_ph": "Büyük başlık",
        "section_body_ph":  "Bölüm içeriği...",
        "section_lbl_clr":  "Etiket Rengi:",
        "section_ttl_clr":  "Başlık Rengi:",
        "section_bdy_clr":  "Paragraf Rengi:",
        "hyperlink_lbl":    "Bağlantı:",
        "hyperlink_text":   "Bağlantı Metni:",
        "hyperlink_url":    "Bağlantı URL:",
        "hyperlink_add":    "➕ Ekle",
        "hyperlink_hint":   "Seçili metni bağlantıya çevir:",
        "sec_add_para":     "+ Paragraf",
        "sec_add_link":     "+ Link Satırı",
        "sec_items_hint":   "İç İçerikler:",
        "sec_item_para":    "¶",
        "sec_item_link":    "🔗",
    },
    "EN": {
        "app_title":        "✉  Newsletter Editor",
        "editor_title":     "✉  NEWSLETTER EDITOR",
        "preview_lbl":      "PREVIEW",
        "newsletter_info":  "NEWSLETTER INFO",
        "subject_ph":       "Subject line / Newsletter title",
        "header_grp":       "HEADER",
        "footer_grp":       "FOOTER",
        "colors_grp":       "COLORS",
        "add_block_grp":    "ADD BLOCK",
        "content_lbl":      "CONTENT BLOCKS",
        "no_img":           "No image selected",
        "img_sel":          "📎 Select PNG",
        "img_clr":          "✕ Clear",
        "bg_color_lbl":     "Content Box Background — Corporate Suggestions:",
        "accent_lbl":       "Accent / Heading Color:",
        "custom_color":     "Custom →",
        "header_bg_lbl":    "Background:",
        "header_txt_lbl":   "Text Color:",
        "footer_text_ph":   "Footer text...",
        "footer_bg_lbl":    "Background:",
        "footer_txt_lbl":   "Text Color:",
        "btn_clear":        "🗑  Clear",
        "btn_load":         "📂  Load",
        "btn_save_proj":    "💾  Save Project",
        "btn_export":       "⬇  Download HTML",
        "btn_copy":         "📋  Copy HTML",
        "btn_refresh":      "🔄",
        "clear_confirm":    "Delete all blocks?",
        "clear_title":      "Clear",
        "saved_title":      "Saved",
        "saved_msg":        "File saved:\n{}",
        "proj_saved":       "Project saved.",
        "copied_title":     "Copied",
        "copied_msg":       "HTML copied to clipboard.",
        "error_title":      "Error",
        "block_add_err":    "Could not add block:\n{}",
        "export_err":       "Export error:\n{}",
        "html_err":         "HTML generation error:<br>{}",
        "no_block_lbl":     "No blocks yet.\nAdd one above ↑",
        "footer_default":   "This email was sent automatically. | © 2025 Your Company",
        "block_heading":    "📌 Heading",
        "block_paragraph":  "📝 Paragraph",
        "block_quote":      "❝ Quote",
        "block_bullet":     "• Bullet List",
        "block_numbered":   "1. Numbered",
        "block_divider":    "─ Divider",
        "block_button":     "🔗 Button",
        "block_image_url":  "🖼 Image URL",
        "block_image_file": "🖼 Image File",
        "block_spacer":     "↕ Spacer",
        "ph_heading":       "Heading text...",
        "ph_paragraph":     "Paragraph text...",
        "ph_quote":         "Quote text...",
        "ph_list":          "One item per line",
        "ph_btn_text":      "Button label",
        "ph_btn_url":       "https://example.com",
        "ph_img_url":       "https://domain.com/image.jpg",
        "ph_img_alt":       "Alt text (optional)",
        "img_select_btn":   "📁 Select File",
        "img_file_lbl":     "No file selected",
        "height_lbl":       "Height (px):",
        "btn_text_lbl":     "Label:",
        "btn_url_lbl":      "URL:",
        "lang_btn":         "🌐 Türkçe",
        "email_footer":     "This email was sent automatically.",
        "two_col":          "2 Columns",
        "one_col":          "1 Column",
        "col_lbl":          "Columns:",
        "hide_subject":     "Hide Subject",
        "hide_footer_txt":  "Hide Footer Text",
        "btn_apply":        "✔ Apply",
        "font_size_lbl":    "Size:",
        "font_family_lbl":  "Font:",
        "btn_clear_content":"🧹 Clear Content",
        "fonts_grp":        "FONT & SIZE",
        "block_url_ph":     "https:// (optional link)",
        "block_url_lbl":    "🔗 URL:",

        "block_section":    "🎨 Section (Dark)",
        "block_toc":        "📋 Table of Contents",
        "block_highlight":  "💡 Highlight Box",
        "block_table":      "📊 Table",
        "block_cards":      "👤 Person Cards",
        "block_emoji_row":  "😊 Emoji Row",
        "hl_success":       "✅ Success (Green)",
        "hl_warning":       "⚠️ Warning (Red)",
        "hl_info":          "ℹ️ Info (Blue)",
        "hl_neutral":       "◻️ Neutral (Grey)",
        "hl_type_lbl":      "Type:",
        "hl_title_ph":      "Title...",
        "hl_body_ph":       "Description...",
        "toc_items_ph":     "Heading 1\nHeading 2\nHeading 3",
        "toc_cols_lbl":     "Columns:",
        "toc_txt_lbl":      "Text Color:",
        "toc_bg_lbl":       "Box Background:",
        "toc_border_lbl":   "Border Color:",
        "tbl_cols_ph":      "Category,Program,Status,Resources",
        "tbl_rows_ph":      "Row1Col1,Row1Col2,Row1Col3,Row1Col4\nRow2Col1,...",
        "card_items_ph":    "Full Name|Title|email@example.com\nFull Name|Title|email@example.com",
        "card_cols_lbl":    "Columns:",
        "card_bg_lbl":      "Card Background:",
        "card_border_lbl":  "Border:",
        "card_avatar_lbl":  "Avatar:",
        "card_name_lbl":    "Name Color:",
        "card_role_lbl":    "Role Color:",
        "card_email_lbl":   "Email Color:",
        "emoji_ph":         "😊 👍 🎉 💡",
        "section_bg_lbl":   "Section Color:",
        "section_txt_lbl":  "Text Color:",
        "section_label_ph": "Small label (e.g. QUICK BRIEFING)",
        "section_title_ph": "Large heading",
        "section_body_ph":  "Section content...",
        "section_lbl_clr":  "Label Color:",
        "section_ttl_clr":  "Title Color:",
        "section_bdy_clr":  "Body Color:",
        "hyperlink_lbl":    "Link:",
        "hyperlink_text":   "Link Text:",
        "hyperlink_url":    "Link URL:",
        "hyperlink_add":    "➕ Add",
        "hyperlink_hint":   "Convert selected text to link:",
        "sec_add_para":     "+ Paragraph",
        "sec_add_link":     "+ Link Row",
        "sec_items_hint":   "Inner Contents:",
        "sec_item_para":    "¶",
        "sec_item_link":    "🔗",
    },
}

# ══════════════════════════════════════════════════════════════════
#  KURUMSAL RENK PALETİ
# ══════════════════════════════════════════════════════════════════
